### PR TITLE
Added ability to grow tacticity-defined polymer chains

### PR DESCRIPTION
**Pull request by sibo**
Added ability to grow tacticity controlled polymer chains using random_walk_taciticity function.
Added examples for polystyrene and vinyl-type polynorobornene
Some edits to allow code to run with Python3
Some edits to allow automatic typing for Br and Si atoms.

### CODE REVIEW

**Comment by AlleksD** [comment]
Hi, Sibo, thank you for the pull request, it is a nice addition to the random_walk functionality. Also, very neat that the tacticity calculation verifies iso/syndio for the PS examples.
Prior to merge, a few relatively minor corrections we would like you to address, please let us know whether you agree/disagree with them:

1. pysimm.apps.random_walk.find_last_tail_vector is duplicated
2. is PS_tacticity_2.mol missing (models.monomers.dreiding.ps_tacticity:6)?

3. In apps.random_walk:750 -- md relaxation happens only every 10 insertions. For some instances this might be not frequent enough, e.g. if a polymer chain structure following random walk is quite far from equilibrium. Suggest making the relaxation frequency a **parameter** with default value of 1.
4. The *tacticity* of the polymer is a float, between 0 and 1. The special keywords "isotatic" and "syndiotactic" are mapped to values of 1 and 0, respectively. A value of 0.4 would give *40% isotactic* insertions and *60% syndiotactic* insertions. Is this ratio designed to be like that, or should be reversed?  
5. Is it possible to release the constraint that capping atoms (H) must be at the first and last positions of the particles list?
6. To make the code appearance consistent would be good to refactor variables and functions to snake_case instead of CamelCase/mixedCase. 
Also, few variables are defined but never used (e.g. random_walk:678, random_walk:722)
7. A suggestion to decrease the number of examples (as they are basically the same) from 4 files to 2 files each of which making 2 different polymers (isotactic and syndiotactic)

**Comment by sibo** [comment]
Hi Alleks,

Thanks for the thorough review! My coding experience was a couple courses in high school/college, and then random small scripting projects for computational chemistry. So having your experienced eye looking over my code is great. I agree with your comments, addressed below

> 1. pysimm.apps.random_walk.find_last_tail_vector is duplicated

SL: Removed duplicate

> 2. is PS_tacticity_2.mol missing (models.monomers.dreiding.ps_tacticity:6)?

SL: Thanks, this was a broken reference to PS_tacticity.mol , and it's been changed.

> 3. In apps.random_walk:750 -- md relaxation happens only every 10 insertions[...]

SL: Good suggestion, I've parameterized the spacing of the MD relaxation steps with md_spacing

> 4. The _tacticity_ of the polymer is a float, between 0 and 1. The special keywords "isotatic" and "syndiotactic" are mapped to values of 1 and 0, respectively. A value of 0.4 would give _40% isotactic_ insertions and _60% syndiotactic_ insertions. Is this ratio designed to be like that, or should be reversed?

SL: Good catch! There was a typo in my README files. A tacticity value of 0.4 will give 40% isotactic insertions (and the remainder will be syndiotactic).  I have adjusted the explanations in the Example README files.

> 5. Is it possible to release the constraint that capping atoms (H) must be at the first and last positions of the particles list?

SL: I believe any elements can be used as capping atoms already. As for the constraint that they must be the first and last atoms in the monomer definition, I will take a closer look. It's been a while since I've looked, so I can't recall why I made that odd programming choice.

Update: I did not succeed. In the step to remove the H head-capping atom in the inserting monomer, somehow the head backbone C shifts over to where the removed head-cap H would have been. I noticed that the original random_walk.random_walk function also used the convention that capping atoms must be first and last in the particle list. If you can release the constraint for the original random_walk function, I could try to adapt that algorithm for random_walk_tacticity, but I do not think I can release this constraint on my own.

> 6. To make the code appearance consistent would be good to refactor variables and functions to snake_case instead of CamelCase/mixedCase. Also, few variables are defined but never used (e.g. random_walk:678, random_walk:722)

SL: done

> 7. A suggestion to decrease the number of examples (as they are basically the same) from 4 files to 2 files each of which making 2 different polymers (isotactic and syndiotactic)

SL: done

**Comment by sibo** [comment]
Hi Alleks, I believe I've addressed all of the issues except for the ability to specify the location of the capping atoms instead of using the first and last atoms in the particle list, as discussed above.

**Comment by AlleksD** [comment]
Hi, Sibo, 

yes, all looks good. Thank you for all modifications on demand, and also thank you for writing and creating .md files!
It took me a while to work with your code, I apologize for that.

I have created an additional pull request that modifies your code a bit; if you think it is good, let's approve that one and afterward this one.


Alex

**Comment by sibo** [comment]
Hi Alleks,

These latest commits are (1) to fix broken references to norbornene .mol files that were moved to a topologies subdirectory and (2) to renumber the Examples so there are not two subdirectories beginning with "12_"

**Review by AlleksD — APPROVED** [review]

**Pull request merged**
